version: '3'
services:
  reverse_proxy:
    image: nginx:latest
    container_name: fs_reverse_proxy
    depends_on:
      - fs_app
      - hs_app1
    volumes:
      - ./reverse_proxy/:/etc/nginx/
      - ./reverse_proxy/html/:/usr/share/nginx/html/
    ports:
      - 80:80
    restart: always
  
  fs_app:
    image: fs_app
    container_name: fs_app
    build:
      context: ./fs_app
    depends_on:
      - hs_app1
    ports: 
      - 3001:3001
    restart: always
  
  hs_app1:
    image: hs_app1
    container_name: hs_app1
    build:
      context: ./hs_app
    ports: 
      - 3003:3003
    restart: always