version: '3'
services:
  reverse_proxy:
    image: nginx:latest
    container_name: fs_reverse_proxy
    depends_on:
      - fs_app
      - hs_app
    volumes:
      - ./reverse_proxy/:/etc/nginx/
      - ./reverse_proxy/html/:/usr/share/nginx/html/
    ports:
      - 80:80

  fs_app:
    image: fs_app
    container_name: fs_app
    build:
      context: ./fs_app
    depends_on:
      - hs_app
    ports: 
      - 3001:3001
  
  hs_app:
    image: hs_app
    container_name: hs_app
    build:
      context: ./hs_app
    ports: 
      - 3002:3002